### ISSUE TITLE
How to call static methods?

### ISSUE THREAD

**Issue by blissi** [kpfromer/nestjs-typegoose#1]
Hallo,

I defined a static method on my Typegoose model and then tried to use the model within a service.
The TypeScript compiler issues an error, though:

> error TS2339: Property 'findAll' does not exist on type 'ModelType<DBShipping>'.

How can I solve this?
Here's my code:

```
export class DBShipping extends Typegoose {
	@staticMethod
	static findAll(this: ModelType<DBShipping> & typeof DBShipping, userId: UserId) {
		....
	}
        ....
}


constructor(@InjectModel(DBShipping) private shippingModel: ModelType<DBShipping>) {
	}

....
const shippings = await this.shippingModel.findAll(context.user.id);
```

Thanks!

**Comment by kpfromer** [comment]
Quick fix for this issue is to add `& typeof DBShipping` to the constructor. It would make the constructor look like this:

```typescript
constructor(@InjectModel(DBShipping) private shippingModel: typeof DBShipping & ModelType<DBShipping>) {
}
```

I will try to find a more elegant approach to this issue though as it might get annoying for users to type `& typeof` everytime they want to use static methods. But I have a feeling that it can't be "fixed." I think thats why [typegoose disscusses why the union is needed.](https://github.com/szokodiakos/typegoose#staticmethod)

**Comment by blissi** [comment]
Thanks for the suggestion, it is working fine!
