### ISSUE TITLE
v5.2.1 issues with forFeature

### ISSUE THREAD

**Issue by duro** [kpfromer/nestjs-typegoose#23]
Was this an expected breaking change? With v5.2.1 I am now getting the following build error:

```
services/nest-example/src/app.module.ts:25:32 - error TS2345: Argument of type 'typeof User' is not assignable to parameter of type '(TypegooseClass<any> | TypegooseClassWithOptions)[]'.
  Type 'typeof User' is missing the following properties from type '(TypegooseClass<any> | TypegooseClassWithOptions)[]': pop, push, concat, join, and 25 more.

25     TypegooseModule.forFeature(User),
```

Nothing in the code on my end has changed.

User extends from Typegoose. I am running version 5.7.1 of Typegoose.

**Comment by kpfromer** [comment]
I changed the way forFeature works. It is now an array of models instead of the older spread because I needed a way to pass in the `connectionName`. So instead of having `TypegooseModule.forFeature(User)` it would be `TypegooseModule.forFeature([User])`
I have also created a [changelog](https://github.com/kpfromer/nestjs-typegoose/blob/master/CHANGELOG.md).

**Comment by krouw** [comment]
if there was a change that breaks the current operation of the library, you should increase to version 6. Recently installed the new version and I had to change all the modules of my project without understanding that there was a change of break.
