### ISSUE TITLE
v5.2 Not Working with Nest TestModule

### ISSUE THREAD

**Issue by krouw** [kpfromer/nestjs-typegoose#25]
Hi! 
When updating to the new version I tried to run my tests and I realized that the library lost its compatibility with Nest TestModule.
I have created a repository where it is possible to recreate the error, when I launch the app with start: dev there are no problems, but when I run the tests, the models are not injected correctly in the service and it displays the following error:

![](https://i.ibb.co/gwZxmsL/error.png)

Link of repository to recreate this issue

https://github.com/krouw/nestjs-typegoose-test

Regards!!!

**Comment by kpfromer** [comment]
Thanks for doing this. I will look into soon.

**Comment by kpfromer** [comment]
I didn't really didn't explain how to unit test with nestjs-typegoose, so sorry about that. Like [@nestjs/mongoose](https://docs.nestjs.com/v5/techniques/mongodb) (see the testing section) nestjs-typegoose's `forFeature` and `forRoot` rely on a database connection to work. In order to unit test your `ProductService` without connecting to a mongo database you need to create a fake model using a [custom provider](https://docs.nestjs.com/fundamentals/custom-providers).

```typescript
import { getModelToken } from "nestjs-typegoose";

...

@Module({
  ProductService,
  {
    provide: getModelToken('Product'),
    useValue: fakeProductModel
  }
})
```
In a spec file this would look like:

```typescript
const module: TestingModule = await Test.createTestingModule({
  providers: [
    {
      provide: getModelToken('Product'),
      useValue: productModel,
    },
    ProductService
  ],
}).compile();
```

The string given to `getModelToken` function should be the class name of the typegoose model.

Thanks for telling me about this. I will update the docs shortly.

**Comment by samdidos** [comment]
Hi, is it possible to access a full working example for this kind of test with mocking?
