### ISSUE TITLE
use of micro-package is-class?

### ISSUE THREAD

**Issue by michaelbats** [kpfromer/nestjs-typegoose#31]
Considering all that's going on with npm and these micro-packages, wouldn't it be a better idea to just move the existing code from is-class as a util part of the source-code, rather than having it on npmjs where there's no guarantees that it will be the same code as in the linked github?

**Comment by kpfromer** [comment]
I would rather use a micro package because I want to separate concerns. I know it is fairly small, but it is just another place this codebase would have to test for. As for "no guarantees that it will be the same code as in the linked GitHub" if they do change the way the package works in a new version we will just have to find an alternative solution.

**Comment by michaelbats** [comment]
Thanks, I'll know not to use this package for any serious project as you clearly don't understand security.
