### ISSUE TITLE
getDiscriminatorModelForClass() is not being used in case where models are sub-typed

### ISSUE THREAD

**Issue by rogrdat** [kpfromer/nestjs-typegoose#36]
@kpfromer Refer details here -- https://typegoose.github.io/typegoose/docs/functions/getDiscriminatorModelForClass/.

With all models created using `getModelForClass` method, `getDiscriminatorModelForClass` is not being used and the discriminator key in schema-options is not being set as a result.  I think the initialization of the model should consider a discriminator when a model is being instantiated.

**Comment by kpfromer** [comment]
Thanks for bringing this up. Just at a glance, I agree with you about there having to be user intervention in order for `nestjs-typegoose` to know that it needs to use `getDiscriminatorModelForClass` instead of `getModelForClass`. I am thinking that there should be a `discriminator` option inside the `forFeature`.

**Comment by rogrdat** [comment]
`forFeature` seems like logical place to start but will probably break the mould of how `forFeature` has been used.  Thoughts on how to go-about it?

**Comment by kpfromer** [comment]
Maybe `forFeature` stores an internal map of classes and compares the constructor of a class to all the others in the internal map (`B.prototype.constructor === A`).
