### ISSUE TITLE
Better setup for development

### ISSUE THREAD

**Issue by kpfromer** [kpfromer/nestjs-typegoose#52]
I think adding a code formatter would reduce style differences better developers. I also think adding a library to lint and format before git adds would be beneficial.
I think that the following libraries would be the best fit to achieve this:

- prettier (and libraries to connect it with eslint)
- husky
- lint-staged

**Comment by hasezoey** [comment]
i would recommend just staying with tslint (instead of using with it with prettier), because prettier is pretty locked down, and all (that i know of) rules that prettier has, tslint does have too
-> many are added in #43

**Comment by kpfromer** [comment]
I was also thinking of moving tslint to eslint with prettier since tslint is [deprecated](https://github.com/palantir/tslint/issues/4534) (or will be very soon). And to my knowledge eslint does not have any formatting just linting.

**Comment by hasezoey** [comment]
i already tried moving typegoose to eslint ~2-3 months back (something might have changed), but at the time i tried, tslint was just superior for typescript because:
- the eslint-tsconfig "wrapper" just didnt support all the rules i need
- tslint-vscode integration is just superior (i mean the deprecated vscode module, because the newer just dosnt work...)
- vscode-eslint is just reporting mostly one character and not the whole statement when something is wrong

> And to my knowledge eslint does not have any formatting just linting.

no, eslint has formatting rules (but way less than tslint, because it would need types to do these rules) 
including all rules that i know of prettier does (except auto-wrap too long lines)
- indent
- indent style (tabs / spaces)
- EOL style (LF / CRLF)
- semicolons ("where-needed" or "always" or "never")
- quote style
- trailing-comma ("where-needed" or "always" or "never")
- bracket-spacing

---

basic stuff eslint & tslint can format:
- adding semicolons if set so (like "where-needed" or "always" or "never")
- extra-last-line (an empty last line in every file)
- setting the EOL to "LF" / "CRLF" / "auto"
- indent spaces to tabs (and vise versa)
- indent correct amount of spaces (tslint never supported this, i still dont know why)
- spacing between "statements" like `const      something    =    true    ;     ` to normal
- converting quotes (singe / double)
- format where curly-braces are
- newline-before-return

**Comment by kpfromer** [comment]
Ok. I will wait until eslint improves to switch over to using it. I do still think that adding `husky` and `lint-staged` will be useful with tslint.
